# Generated by Django 3.1.6 on 2021-02-07 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagen',
            name='fecha',
            field=models.DateTimeField(default=None, verbose_name='date published'),
        ),
    ]
