# Generated by Django 3.1.6 on 2021-02-07 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0002_imagen_fecha'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagen',
            name='fecha',
        ),
    ]
