# Generated by Django 3.1.6 on 2021-02-07 19:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0005_auto_20210207_1945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagen',
            name='fecha',
            field=models.DateField(default=datetime.date(2021, 2, 7), verbose_name='date published'),
        ),
    ]
