# Generated by Django 3.1.6 on 2021-02-07 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0008_auto_20210207_1954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagen',
            name='fecha',
            field=models.DateField(blank=True, null=True),
        ),
    ]
