# Generated by Django 3.1.6 on 2021-02-07 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('galeria', '0010_auto_20210207_2001'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagen',
            name='usuario',
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
